# fonts
font_family JetBrainsMono
bold_font auto
italic_font auto
bold_italic_font auto

# cursor
cursor_shape block

# scrolling
scrollback_lines 2000

# BEGIN_KITTY_THEME
# Kanagawa
include current-theme.conf
# END_KITTY_THEME

# keybinds
kitty_mod super

map kitty_mod+enter new_window
map kitty_mod+x close_window
map kitty_mod+n next_window
map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_from_clipboard
map kitty_mod+f toggle_fullscreen
