on:
  push:
    branches:
      - 'main'
  pull_request:

name: "CI/Test"
permissions: {}

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC1090 -e SC1091
        with:
          severity: warning
          ignore_paths: >-
            dotbot
            vim
          ignore_names: bashrc
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: |
          mkdir -p ~/dotfiles-install-dir
      - run: |
          HOME=~/dotfiles-install-dir ./install
