on:
  push:
    branches:
      - 'main'
    paths:
      - '**.sh'

name: "Trigger: Push action"
permissions: {}

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC1090 -e SC1091
        with:
          severity: warning
          ignore_paths: >-
            dotbot
            vim
          ignore_names: bashrc
